[package]
name = "zkjwt"
type = "bin"
authors = ["Rasul Ibragimov"]
compiler_version = ">=1.0.0"

[dependencies]
jwt = { tag = "v0.5.1", git = "https://github.com/zkemail/noir-jwt" }
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }