[book]
title = "Social Recovery SDK"
authors = ["Rasul Ibragimov"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/social-recovery-sdk/"
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
