name: Circuits

on:
  push:
    paths:
      - "circuits/**"
  pull_request:
    paths:
      - "circuits/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: stable

      - name: Build
        working-directory: circuits/zkjwt
        run: nargo build

      - name: Test
        working-directory: circuits/zkjwt
        run: nargo test
